### ISSUE TITLE
Request: ICE - Overexchange Condenser

### ISSUE THREAD

**Issue by darkniko** [sparticle999/SpaceCompany#300]
Can Helium resource requirement be 204.000 instead of 205.000_ please... 

![image](https://user-images.githubusercontent.com/24360651/30838126-16ec19e0-a240-11e7-9550-2c604723ec38.png)

**Comment by idjlak** [comment]
Is the odd number 5 disturbing you or does it cross a difficult threshold?

**Comment by IsaacPYoung** [comment]
204,800 is a storage threshold. The pricing looks intentional to me.

**Comment by darkniko** [comment]
Jumping from T3 to T5 machines makes it a bit difficult

**Comment by sparticle999** [comment]
It's not intentional. I mainly use random numbers that seem in the vicinity of where they should be for balance. Player's style adapts based on costs, so it may not look balanced immediately, but over the long run if it stays, it becomes balanced without having to do anything ^_^. But yeah, I'll move it down to 204K

**Comment by darkniko** [comment]
TNK U!!! >D
