### ISSUE TITLE
Plasma EMC

### ISSUE THREAD

**Issue by Rhynchocephale** [sparticle999/SpaceCompany#307]
When converting more than 10k Plasma into Meteorite through EMC, the full amount of plasma is never used and 10k Plasma are left untouched. This does not happen when converting Energy, in which case none is left.
I think the Plasma, too, should be converted until there is none left.

**Comment by darkniko** [comment]
True, happened to me all day long today.. Also 2 more things so i dont keep posting new threads just for 2 lines of text.

I notices the past few days, while i must have rebirth almost 10 times. That the most difficult part in early game is reaching 50M Science. Its funny even because it takes me about 12 hours to reach that amount. Its like everything is so fast and it makes a very big contraste with all the rest thats happening in the game. Because suddenly BOOOM 50M science requirement ..

Meteorite in Resource TAB when it fills up, for storage upgrading, takes a few moments to really fill up, even though its already at max capacity.

**Comment by sparticle999** [comment]
This is intentional and I believe I have made this clear in a note at the top. I should do the same with energy, I agree. But this was done to stop a bug destroying meteorite production due to the deficit of plasma stored. 

Sparticle999
